INSERT INTO COUNTRY (ID,NAME) VALUES(1,'Türkiye');
INSERT INTO COUNTRY (ID,NAME) VALUES(2,'Almanya');
INSERT INTO COUNTRY (ID,NAME) VALUES(3,'Fransa');

INSERT INTO CITY (ID, NAME,COUNTRY_ID) VALUES(1,'Berlin',2);
INSERT INTO CITY (ID, NAME,COUNTRY_ID) VALUES(3,'Paris',3);
INSERT INTO CITY (ID, NAME,COUNTRY_ID) VALUES(2,'Istanbul',1);
INSERT INTO CITY (ID, NAME,COUNTRY_ID) VALUES(4,'Bursa',1);

INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(1,'IST','İstanbul Havalimanı',1);
INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(2,'ESB','Esenboğa Havalimanı',1);
INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(3,'ADB','Adnan Menderes Havalimanı',1);
INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(4,'AYT','Antalya Havalimanı',2);
INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(5,'DLM','Dalaman Havalimanı',2);
INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(6,'BJV','Milas-Bodrum Havalimanı',2);
INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(7,'TZX','Trabzon Havalimanı',3);
INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(8,'FRA','Frankfurt Havalimanı',3);
INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(9,'MUC','Franz Josef Strauss Havalimanı',3);
INSERT INTO AIRPORT (ID,CODE, NAME,CITY_ID) VALUES(10,'TXL','Berlin Tegel Havalimanı',3);


