INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(1,'IST','İstanbul Havalimanı');
INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(2,'ESB','Esenboğa Havalimanı');
INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(3,'ADB','Adnan Menderes Havalimanı');
INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(4,'AYT','Antalya Havalimanı');
INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(5,'DLM','Dalaman Havalimanı');
INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(6,'BJV','Milas-Bodrum Havalimanı');
INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(7,'TZX','Trabzon Havalimanı');
INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(8,'FRA','Frankfurt Havalimanı');
INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(9,'MUC','Franz Josef Strauss Havalimanı');
INSERT INTO AIRPORT (ID,CODE, NAME) VALUES(10,'TXL','Berlin Tegel Havalimanı');

INSERT INTO COUNTRY (ID, CITY, COUNTRY, AIRPORT_ID) VALUES(1,'Istanbul','Türkiye',1);
INSERT INTO COUNTRY (ID, CITY, COUNTRY, AIRPORT_ID) VALUES(2,'Ankara','Türkiye',2);
INSERT INTO COUNTRY (ID, CITY, COUNTRY, AIRPORT_ID) VALUES(3,'Izmir','Türkiye',3);
INSERT INTO COUNTRY (ID, CITY, COUNTRY, AIRPORT_ID) VALUES(4,'Antalya','Türkiye',4);
INSERT INTO COUNTRY (ID, CITY, COUNTRY, AIRPORT_ID) VALUES(5,'Dalaman','Türkiye',5);
INSERT INTO COUNTRY (ID, CITY, COUNTRY, AIRPORT_ID) VALUES(6,'Frankfurt','Almanya',8);
INSERT INTO COUNTRY (ID, CITY, COUNTRY, AIRPORT_ID) VALUES(7,'Münih','Almanya',9);
INSERT INTO COUNTRY (ID, CITY, COUNTRY, AIRPORT_ID) VALUES(8,'Berlin','Almanya',10);
